name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Ragulvl
          gif_out_path: output/github-snake.gif
          svg_out_path: output/github-snake.svg
      - uses: Platane/snk@v3
        id: snake-gif-dark
        with:
          github_user_name: Ragulvl
          gif_out_path: output/github-snake-dark.gif
          svg_out_path: output/github-snake-dark.svg
          snake_color: "0:0:0"
      - name: push to github
        uses: git-auto-commit-action@v5
        with:
          commit_message: "Generate contribution snake"
